### ISSUE TITLE
Fails to write output to file if containing directory does not yet exist

### ISSUE THREAD

**Issue by eddieaich** [jakubpawlowicz/clean-css-cli#36]
If I try to output to a file in a target directory but that directory does not yet exist, the system throws an error. This does not happen if I use grunt-contrib-cssmin - it creates the missing directory structure for me, but I no longer want to use grunt. Here is the stack trace on a Windows 10 OS:

`Error: ENOENT: no such file or directory, open 'C:\Users\Human\Documents\GitHub\crucial\public\dist\1.0.0\css\main.min.css'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at output (C:\Users\Human\Documents\GitHub\crucial\node_modules\clean-css-cli\index.js:323:8)
    at C:\Users\Human\Documents\GitHub\crucial\node_modules\clean-css-cli\index.js:266:7
    at C:\Users\Human\Documents\GitHub\crucial\node_modules\clean-css\lib\clean.js:125:9
    at C:\Users\Human\Documents\GitHub\crucial\node_modules\clean-css\lib\reader\read-sources.js:26:64
    at loadOriginalSources (C:\Users\Human\Documents\GitHub\crucial\node_modules\clean-css\lib\reader\load-original-sources.js:26:5)
    at C:\Users\Human\Documents\GitHub\crucial\node_modules\clean-css\lib\reader\read-sources.js:26:14
    at applySourceMaps (C:\Users\Human\Documents\GitHub\crucial\node_modules\clean-css\lib\reader\apply-source-maps.js:34:5)
    at Object.callback (C:\Users\Human\Documents\GitHub\crucial\node_modules\clean-css\lib\reader\read-sources.js:25:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crucial-core@1.0.0 cleancss: `cleancss -o public/dist/%npm_package_version%/css/main.min.css public/css/*.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crucial-core@1.0.0 cleancss script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by jakubpawlowicz** [comment]
It's fixed in main branch and due in v5.0.0 soon.
